/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as ierc721BigBrainSol from "./IERC721BigBrain.sol";
export type { ierc721BigBrainSol };
export type { CoinFlip } from "./CoinFlip";
export type { ICoinFlip } from "./ICoinFlip";
export type { Lock } from "./Lock";
