/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export * as ierc721BigBrainSol from "./IERC721BigBrain.sol";
export { CoinFlip__factory } from "./CoinFlip__factory";
export { ICoinFlip__factory } from "./ICoinFlip__factory";
export { Lock__factory } from "./Lock__factory";
